locations:
    hub:
        x: 0
        y: 128
        z: 0
    point1:
        x: 0
        y: 128
        z: 0
    point2:
        x: 0
        y: 128
        z: 0
    point3:
        x: 0
        y: 128
        z: 0
    point4:
        x: 0
        y: 128
        z: 0

mapName: "herobattle"
gameName: "herobattle"
