name: HeroBattle
description: Dev Plugin
main: net.lnfinity.HeroBattle.HeroBattle
version: 0.1

depend:
 - MasterBundle


commands:
  start:
    description: Force le démarrage du jeu.
    usage: Vous n'avez pas les permissions requises !

  forcestop:
    description: Force l'arrêt du jeu. Sachez ce que vous faites !
    aliases: [fstop]
    usage: Vous n'avez pas les permissions requises !

  powerup:
    description: Provoque l'apparition d'un powerup (si une place est libre).
    usage: Vous n'avez pas les permissions requises !

  classe:
    description: Permet de choisir une classe.
    aliases: [class]
    usage: /classe <classe>
  
  elo:
    description: Modifie l'elo d'un joueur.
    aliases: [elo]
    usage: Vous n'avez pas les permissions requises !
