name: HeroBattle
description: Dev Plugin
main: net.lnfinity.HeroBattle.HeroBattle
version: 0.1

depend:
 - MasterBundle


commands:
  start:
    description: Force le démarrage du jeu.
    aliases: [start]
    usage: Vous n'avez pas les permissions requises !
  forcestop:
    description: Force l'arrêt du jeu. Sachez ce que vous faites !
    aliases: [forcestop]
    usage: Vous n'avez pas les permissions requises !