locations:
    point1:
        x: 0
        y: 128
        z: 0
    point2:
        x: 0
        y: 128
        z: 0
    point3:
        x:
        y:
        z:
    point4:
        x:
        y:
        z: